### ISSUE TITLE
How can I use the controller to Move Forward?

### ISSUE THREAD

**Issue by soawesome233** [Renzo904/BetterDivaPractice#1]
If not, may I ask if it will be implemented in the future? I really need it, thank you very much

**Comment by Renzo904** [comment]
I'm sorry for the late response, I kinda left the project abandoned with uni and work, no, currently there is no equivalent to "shift" in controller, I'm planning to see if it's possible, which button would you think is best suited for that?

**Comment by soawesome233** [comment]
I think everything is appropriate and I'm not sure which button is suitable because all the buttons on the controller are used by the game. I think only LS and RS, which default to controlling backward and forward, are suitable for modification. Also, I'm not sure if the controller can use combination keys, so it's up to you to decide in the end. Of course, learning and work are priority, and I wish you all the best

**Comment by Renzo904** [comment]
For now i added it to Right Shoulder + Left Stick(or R1 + L3), this of course is subject to discussion
